### ISSUE TITLE
Problemas con  colspan y Rowspan

### ISSUE THREAD

**Issue by davidfaguas** [pjjonesnz/datatables-buttons-excel-styles#5]
Hola Estimado Paul, nuevamente David Faguas, ahora tengo otro problema estoy generando una tabla con varias columnas en la cuales estoy ulizando colspan y Rowspan para sus encabezados, pero no me carga el botón para exportar a excel a continuación te comparto el fuente:

https://plnkr.co/edit/brkG2tQqn49vNVLn?open=lib%2Fscript.js&preview

este error me arroja en la consola:

![image](https://user-images.githubusercontent.com/68312475/121830532-3e280100-cc93-11eb-865d-5e264b42a699.png)

**Comment by pjjonesnz** [comment]
Hi @davidfaguas 

Unfortunately this problem is to do with the Datatables plugin, not my style plugin.

If you remove the buttons plugin (which gives you the excel button) and my style plugin, you still get the same error: https://plnkr.co/edit/UxVeIqRyGtGSV92U?open=lib%2Fscript.js

You would need to talk to the [Datatables.net ](https://datatables.net/) team to see if they know what is causing this.

I have had a look but can't see what the problem is.

Sorry that I am unable to help with this.

Kind regards
Paul

**Comment by davidfaguas** [comment]
Muchas gracias por tu respuesta tan rápida, Saludos Paul.

**Comment by pjjonesnz** [comment]
Hi @davidfaguas 

I found the problem.  The table has to be perfect for dataTables to work.

There was a cell missing in your first data row, and some of your header rows had rowspan="3" instead of rowspan="2"

Here is the fixed page: https://plnkr.co/edit/HxeXzu1U0eEBvjm8?open=lib%2Fscript.js&preview

:)

**Comment by davidfaguas** [comment]
ohhhh amigo muchas gracias te pasaste 100% funciono bien gracias ahora lo del encabezado del colspan y rowspan intentare añadirlas al momento de exportarla al excel.

**Comment by pjjonesnz** [comment]
You are very welcome. :)
